import React from 'react';
import { motion } from 'framer-motion';
import Button from '../ui/Button';

export default function FinalCta() {
  return (
    <section className="py-24 relative overflow-hidden">
      <div className="absolute inset-0 bg-gradient-to-br from-brand-blue/10 to-brand-orange/5" />
      
      <div className="max-w-4xl mx-auto px-6 text-center relative z-10">
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          whileInView={{ opacity: 1, scale: 1 }}
          viewport={{ once: true }}
          className="glass rounded-3xl p-12 border border-brand-blue/20 shadow-[0_0_50px_rgba(59,130,246,0.15)] bg-dark-surface/80"
        >
          <h2 className="text-4xl md:text-5xl font-black mb-6 text-white tracking-tight font-outfit">
            Ready to Supercharge <br className="hidden sm:block" />
            Your <span className="text-brand-orange">AI Security?</span>
          </h2>
          <p className="text-gray-300 text-lg mb-8 max-w-xl mx-auto leading-relaxed">
            Protect production database queries generated by AI agents with a secure, zero-knowledge AST firewall gateway.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Button size="lg" className="w-full sm:w-auto shadow-[0_0_20px_rgba(249,115,22,0.3)] bg-brand-orange hover:bg-orange-600 border-none" onClick={() => window.location.href = '/adminzero'}>
              Deploy AdminZero
            </Button>
            <Button variant="secondary" size="lg" className="w-full sm:w-auto" onClick={() => document.getElementById('contact-form')?.scrollIntoView({ behavior: 'smooth' })}>
              Request Enterprise Demo
            </Button>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
