import React from 'react';
import { motion } from 'framer-motion';
import { Link2, Shield, Terminal, Activity, ChevronRight } from 'lucide-react';

const steps = [
  {
    number: "01",
    icon: <Link2 className="text-indigo-400" size={20} />,
    title: "Connect Your Data Layer",
    desc: "Log into the AdminZero Config Portal, click 'Connect Database', and input your target database URI. AdminZero immediately generates an isolated, low-latency proxy connection endpoint.",
    subtext: "Input: postgres://your-db.aws.com:5432"
  },
  {
    number: "02",
    icon: <Shield className="text-indigo-400" size={20} />,
    title: "Define Your AST Firewall Policy",
    desc: "Select your agent's permission profile using simple dashboard toggles. Enforce a strict 'STRICT_READ_ONLY' policy to block all structural alterations, or compile custom rules to allow specific INSERT/UPDATE operations on targeted tables.",
    subtext: "Policy Selected: BLOCK_ALL_DDL_AND_MODIFICATIONS"
  },
  {
    number: "03",
    icon: <Terminal className="text-indigo-400" size={20} />,
    title: "Swap Your Agent's Connection String",
    desc: "Update your AI agent or backend database driver configuration. Instead of connecting directly to your raw production database, point your connection pool to your secure, local AdminZero Proxy URI.",
    code: "const db = new Pool({ connectionString: 'postgres://proxy.adminzero.in:8080' });"
  },
  {
    number: "04",
    icon: <Activity className="text-indigo-400" size={20} />,
    title: "Real-Time SecOps Monitoring",
    desc: "Your agent is now fully insulated. Every query generated by the LLM is intercepted and deep-scanned in under 4ms. View real-time AST breakdown streams, threat logs, and compliance trails directly from your central AdminZero Audit Dashboard.",
    subtext: "Live Status: Streaming AST logs | 0 Threats Detected"
  }
];

export default function SecurityOnboarding() {
  return (
    <section className="py-24 relative overflow-hidden bg-dark-bg border-t border-white/5">
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[70%] h-[70%] bg-indigo-600/5 rounded-full blur-[160px] pointer-events-none" />

      <div className="max-w-7xl mx-auto px-6 relative z-10">
        <div className="text-center mb-16 flex flex-col items-center">
          <motion.div 
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-xs font-semibold uppercase tracking-widest text-indigo-400 mb-4"
          >
            ⚡ Deployment Guide
          </motion.div>
          
          <motion.h2 
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.1 }}
            className="text-3xl md:text-5xl font-black mb-6 tracking-tight text-white font-outfit"
          >
            Deploy Security In 4 Steps
          </motion.h2>
        </div>

        {/* Responsive Stepper Container */}
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-8 max-w-7xl mx-auto relative">
          {steps.map((step, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: idx * 0.1 }}
              className="flex flex-col bg-white/[0.01] border border-white/5 p-6 rounded-3xl relative hover:border-white/10 transition-all group"
            >
              {/* Stepper connector lines on desktop */}
              {idx < steps.length - 1 && (
                <div className="hidden lg:flex items-center absolute top-10 right-[-24px] w-8 z-20 text-white/10 group-hover:text-indigo-500/40 transition-colors">
                  <ChevronRight size={20} />
                </div>
              )}

              <div className="flex items-center justify-between mb-4">
                <div className="p-2.5 bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 rounded-xl">
                  {step.icon}
                </div>
                <span className="font-mono text-xs font-bold text-gray-600 group-hover:text-indigo-400 transition-colors">
                  STEP {step.number}
                </span>
              </div>

              <div className="space-y-3 flex-1 flex flex-col justify-between">
                <div>
                  <h3 className="text-sm font-bold text-white group-hover:text-indigo-300 transition-colors font-mono">
                    {step.title}
                  </h3>
                  <p className="text-xs text-gray-400 leading-relaxed mt-2">
                    {step.desc}
                  </p>
                </div>

                <div className="pt-4 border-t border-white/[0.04]">
                  {step.code ? (
                    <div className="font-mono text-[9px] bg-zinc-950 p-2.5 rounded-lg border border-white/5 text-emerald-400 overflow-x-auto">
                      <code>{step.code}</code>
                    </div>
                  ) : (
                    <div className="font-mono text-[9px] text-indigo-400/80 bg-indigo-950/20 border border-indigo-500/10 p-2 rounded-lg truncate">
                      <code>{step.subtext}</code>
                    </div>
                  )}
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
